src/Entity/Event.php
<?php

/**
 * Event class file
 *
 * PHP Version 7.1
 *
 * @category Event
 * @package  Event
 * @author   HumanAid <contact.humanaid@gmail.com>
 * @license  http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link     http://example.com/
 */

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Event class
 *
 * The class holding the root Event class definition
 *
 * @category Event
 * @package  Event
 * @author   HumanAid <contact.humanaid@gmail.com>
 * @license  http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link     http://example.com/
 * @ORM\Table(name="event")
 * @ORM\Entity(repositoryClass="App\Repository\EventRepository")
 */
class Event
{
    /**
     * ID attribute
     *
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * Title attribute
     *
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * Description attribute
     *
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * User attribute
     *
     * @ORM\ManyToOne(
     *     targetEntity="App\Entity\User",
     *     inversedBy="events"
     * )
     * @ORM\JoinColumn(
     *     name="owner_id",
     *     referencedColumnName="id",
     *     onDelete="CASCADE"
     * )
     */
    private $owner;

    /**
     * Category attribute
     *
     * @ORM\ManyToMany(
     *     targetEntity="App\Entity\EventCategory",
     *     mappedBy="events"
     * )
     */
    private $categories;

    /**
     * Start date attribute
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $start_date;

    /**
     * End date attribute
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $end_date;

    /**
     * Publish date attribute
     *
     * @ORM\Column(type="datetime")
     */
    private $publish_date;

    /**
     * Rating attribute
     *
     * @ORM\OneToMany(targetEntity="App\Entity\Rating", mappedBy="event")
     */
    private $ratings;

    /**
     * Rating attribute
     *
     * @ORM\Column(type="float", nullable=true)
     */
    private $rating;

    /**
     * Event constructor.
     */
    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->ratings = new ArrayCollection();
    }

    /**
     * ID Getter
     *
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Title Getter
     *
     * @return mixed
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Title Setter
     *
     * @param string $title Title
     *
     * @return Event
     */
    public function setTitle($title): self
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Description Getter
     *
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Description Setter
     *
     * @param string $description Description
     *
     * @return Event
     */
    public function setDescription($description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * User Getter
     *
     * @return mixed
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     * User Setter
     *
     * @param User $owner owner
     *
     * @return Event
     */
    public function setOwner($owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    /**
     * Categories Getter
     *
     * @return Collection|EventCategory[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    /**
     * Categories Collection Setter
     *
     * @param EventCategory $category Category
     *
     * @return $this
     */
    public function addCategory(EventCategory $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->addEvent($this);
        }

        return $this;
    }

    /**
     * Categories Collection Remover
     *
     * @param EventCategory $category Category
     *
     * @return $this
     */
    public function removeCategory(EventCategory $category): self
    {
        if ($this->categories->contains($category)) {
            $this->categories->removeElement($category);
        }

        return $this;
    }

    /**
     * Start date Getter
     *
     * @return mixed
     */
    public function getStartDate()
    {
        return $this->start_date;
    }

    /**
     * Start date Setter
     *
     * @param Datetime $start_date Start date
     *
     * @return Event
     */
    public function setStartDate($start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    /**
     * End date Getter
     *
     * @return mixed
     */
    public function getEndDate()
    {
        return $this->end_date;
    }

    /**
     * End date Setter
     *
     * @param DateTime $end_date End date
     *
     * @return Event
     */
    public function setEndDate($end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    /**
     * Publish date Getter
     *
     * @return mixed
     */
    public function getPublishDate()
    {
        return $this->publish_date;
    }

    /**
     * Publish date Setter
     *
     * @param DateTime $publish_date Publish date
     *
     * @return Event
     */
    public function setPublishDate($publish_date): self
    {
        $this->publish_date = $publish_date;

        return $this;
    }

    /**
     * Ratings Getter
     *
     * @return Collection
     */
    public function getRatings(): Collection
    {
        return $this->ratings;
    }

    /**
     * Ratings Adder
     *
     * @param Rating $rating Rating
     *
     * @return $this
     */
    public function addRating(Rating $rating): self
    {
        if (!$this->ratings->contains($rating)) {
            $this->ratings[] = $rating;
            $rating->setEvent($this);
        }

        return $this;
    }

    /**
     * Ratings Remover
     *
     * @param Rating $rating Rating
     *
     * @return $this
     */
    public function removeRating(Rating $rating): self
    {
        if ($this->ratings->contains($rating)) {
            $this->ratings->removeElement($rating);
            // set the owning side to null (unless already changed)
            if ($rating->getEvent() === $this) {
                $rating->setEvent(null);
            }
        }

        return $this;
    }

    /**
     * Rating Getter
     *
     * @return mixed
     */
    public function getRating()
    {
        return $this->rating;
    }

    /**
     * Rating Setter
     *
     * @param int $rating Rating
     *
     * @return Event
     */
    public function setRating($rating): self
    {
        $this->rating = $rating;

        return $this;
    }
}

src/Form/EventType.php
<?php

/**
 * EventType class file
 *
 * PHP Version 7.1
 *
 * @category EventType
 * @package  EventType
 * @author   HumanAid <contact.humanaid@gmail.com>
 * @license  http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link     http://example.com/
 */

namespace App\Form;

use App\Entity\Event;
use App\Entity\EventCategory;
use App\Entity\User;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * EventType class
 *
 * The class holding the root EventType class definition
 *
 * @category EventType
 * @package  EventType
 * @author   HumanAid <contact.humanaid@gmail.com>
 * @license  http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link     http://example.com/
 */
class EventType extends AbstractType
{
    /**
     * Build a form for rating/comment
     *
     * @param FormBuilderInterface $builder build the form
     * @param array                $options got options
     *
     * @return void
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'title',
            TextType::class,
            [
                'label'       => 'Titre :',
                'required'    => true,
                'attr'        => [
                    'class'   => 'form-control'
                ],
                'constraints' => [
                    new NotBlank()
                ]
            ]
        )->add(
            'description',
            TextareaType::class,
            [
                'label'       => 'Description :',
                'required'    => true,
                'attr'        => [
                    'class'   => 'form-control'
                ],
                'constraints' => [
                    new NotBlank()
                ]
            ]
        )->add(
            'start_date',
            DateTimeType::class,
            [
                'label'       => 'Date de début :',
                'date_widget' => 'single_text',
                'time_widget' => 'single_text'
            ]
        )->add(
            'end_date',
            DateTimeType::class,
            [
                'label'       => 'Date de fin :',
                'date_widget' => 'single_text',
                'time_widget' => 'single_text'
            ]
        )->add(
            'owner',
            EntityType::class,
            [
                'label'        => 'Association :',
                'required'     => false,
                'class'        => User::class,
                'choice_label' => 'name',
                'attr'         => [
                    'class'    => 'form-control'
                ],
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->where("'[\"ROLE_ASSOC\"]' = u.roles");
                },
            ]
        )->add(
            'categories',
            EntityType::class,
            [
                'label'      => 'Categories :',
                'attr'       => [
                    'class'  => 'form-control'
                ],
                'class'        => EventCategory::class,
                'choice_label' => 'label',
                'multiple'     => true,
            ]
        );
    }

    /**
     * Configure form
     *
     * @param OptionsResolver $resolver set default parameters
     *
     * @return void
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class'      => Event::class,
                'csrf_protection' => true,
                'csrf_field_name' => '_token',
                'csrf_token_id'   => 'event_item',
            ]
        );
    }
}

src/Controller/EventController.php
<?php

/**
 * EventController class file
 *
 * PHP Version 7.1
 *
 * @category EventController
 * @package  EventController
 * @author   HumanAid <contact.humanaid@gmail.com>
 * @license  http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link     http://example.com/
 */

namespace App\Controller;

use App\Entity\Event;
use App\Entity\Rating;
use App\Entity\EventCategory;
use App\Form\EventType;
use App\Repository\EventRepository;
use App\Repository\RatingRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

/**
 * EventController class
 *
 * The class holding the root EventController class definition
 *
 * @category EventController
 * @package  EventController
 * @author   HumanAid <contact.humanaid@gmail.com>
 * @license  http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link     http://example.com/
 *
 * @Route("/event")
 */
class EventController extends AbstractController
{
    /**
     * Index Function
     *
     * @param EventRepository $eventRepository get event repository
     *
     * @Route("/", name="event_index", methods={"GET"})
     *
     * @return Response
     */
    public function index(EventRepository $eventRepository): Response
    {
        return $this->render(
            'event/index.html.twig',
            [
                'events' => $eventRepository->findAll(),
            ]
        );
    }

    /**
     * New Function
     *
     * @param Request $request get request params
     *
     * @Route("/new", name="event_new", methods={"GET","POST"})
     *
     * @return Response
     * @throws \Exception
     */
    public function new(Request $request): Response
    {
        $form  = $this->createForm(EventType::class, $event = new Event());
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if (!$this->isCsrfTokenValid(
                'event_item',
                $request->request->get('event')['_token']
            )
            ) {
                throw new AccessDeniedException('Formulaire invalide');
            }

            $entityManager = $this->getDoctrine()->getManager();

            /**
             * Event category
             *
             * @var EventCategory $category
             */
            foreach ($form->get('categories')->getData() as $category) {
                $event->addCategory($category);
            }

            $event->setPublishDate(new \DateTime());
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('event_index');
        }

        return $this->render(
            'event/new.html.twig',
            [
                'event' => $event,
                'form' => $form->createView(),
            ]
        );
    }

    /**
     * Show Function
     *
     * @param Event $event get event to show
     *
     * @Route("/{id}", name="event_show", methods={"GET"})
     *
     * @return Response
     */
    public function show(Event $event): Response
    {
        return $this->render(
            'event/show.html.twig',
            [
                'event' => $event,
            ]
        );
    }

    /**
     * ListRating Function
     *
     * @param RatingRepository $ratingRepository get rating repository
     *
     * @Route("/rating/{id}", name="event_list_rating", methods={"GET"},)
     * 
     *
     * @return Response
     */
    public function listrating(RatingRepository $ratingRepository, Request $request, Rating $rating ): Response
    {
        $ratingRepository = $this->getDoctrine()->getManager()
            ->getRepository(Rating::class);

        $id = $request->get("id");
        $result = $ratingRepository->findByEvent($id);



        return $this->render(
            'rating/index.html.twig',
            [
                'ratings' => $result,
            ]
        );
    }

    /**
     * Edit Function
     *
     * @param Request $request get request params
     * @param Event   $event   get event to edit
     *
     * @Route("/{id}/edit", name="event_edit", methods={"GET","POST"})
     *
     * @return Response
     */
    public function edit(Request $request, Event $event): Response
    {
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if (!$this->isCsrfTokenValid(
                'event_item',
                $request->request->get('event')['_token']
            )
            ) {
                throw new AccessDeniedException('Formulaire invalide');
            }
            
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('event_index');
        }

        return $this->render(
            'event/edit.html.twig',
            [
                'event' => $event,
                'form' => $form->createView(),
            ]
        );
    }

    /**
     * Delete Function
     *
     * @param Request $request get request params
     * @param Event   $event   get event to delete
     *
     * @Route("/{id}", name="event_delete", methods={"DELETE"})
     *
     * @return Response
     */
    public function delete(Request $request, Event $event): Response
    {
        if ($this->isCsrfTokenValid(
            'delete'.$event->getId(),
            $request->request->get('_token')
        )
        ) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($event);
            $entityManager->flush();
        }

        return $this->redirectToRoute('event_index');
    }
}

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('event_delete', {'id': event.id}) }}" onsubmit="return confirm('Êtes vous sûre de vouloir faire ca ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/event/_form.html.twig
{{ form_start(form) }}
    {{ form_row(form._token) }}
    {{ form_errors(form) }}
    <div class="form-group">
        {{ form_label(form.title) }}
        {{ form_widget(form.title) }}
        {% if form_errors(form.title) %}
            <div class="alert alert-danger" role="alert">
                {{ form_errors(form.title) }}
            </div>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form_label(form.description) }}
        {{ form_widget(form.description) }}
        {% if form_errors(form.description) %}
            <div class="alert alert-danger" role="alert">
                {{ form_errors(form.description) }}
            </div>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form_label(form.owner) }}
        {{ form_widget(form.owner) }}
        {% if form_errors(form.owner) %}
            <div class="alert alert-danger" role="alert">
                {{ form_errors(form.owner) }}
            </div>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form_label(form.categories) }}
        {{ form_widget(form.categories) }}
        {% if form_errors(form.categories) %}
            <div class="alert alert-danger" role="alert">
                {{ form_errors(form.categories) }}
            </div>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form_label(form.start_date) }}
        {{ form_widget(form.start_date) }}
        {% if form_errors(form.start_date) %}
            <div class="alert alert-danger" role="alert">
                {{ form_errors(form.start_date) }}
            </div>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form_label(form.end_date) }}
        {{ form_widget(form.end_date) }}
        {% if form_errors(form.end_date) %}
            <div class="alert alert-danger" role="alert">
                {{ form_errors(form.end_date) }}
            </div>
        {% endif %}
    </div>
    <div class="form-group">
        <button class="btn btn-success">{{ button_label|default('Enregistrer') }}</button>
    </div>
{{ form_end(form, {'render_rest': false}) }}

templates/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifications - Evenements{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
            <a class="btn btn-light" href="{{ path('event_index') }}">Retour</a>
        </div>
        <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2" style="text-align: right">
            {{ include('event/_delete_form.html.twig') }}
        </div>
    </div>

    <div class="row-fluid">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            {{ include('event/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
        </div>
    </div>
{% endblock %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Evenements{% endblock %}

{% block body %}
    <div class="row-fluid">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="text-align: right">
            <a class="btn btn-success" href="{{ path('event_new') }}">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Ajouter
            </a>
        </div>
    </div>

    <div class="row-fluid">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <table class="table table-global">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Titre</th>
                    <th>Description</th>
                    <th>Date de début</th>
                    <th>Date de fin</th>
                    <th>Date de publication</th>
                    <th>Association</th>
                    <th>Note</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for event in events %}
                    <tr>
                        <td>{{ event.id }}</td>
                        <td>{{ event.title }}</td>
                        <td>{{ event.description }}</td>
                        <td>{{ event.startDate ? event.startDate|date('Y-m-d H:i:s') : '' }}</td>
                        <td>{{ event.endDate ? event.endDate|date('Y-m-d H:i:s') : '' }}</td>
                        <td>{{ event.publishDate ? event.publishDate|date('Y-m-d H:i:s') : '' }}</td>
                        <td>{{ event.owner ? event.owner.name : '' }}</td>
                        <td>{{ event.rating }}</td>
                        <td class="actions">
                            <a class="btn btn-info" href="{{ path('event_show', {'id': event.id}) }}" style="width: 50%;display:inline;">
                                Voir
                            </a>
                            <a class="btn btn-primary" href="{{ path('event_edit', {'id': event.id}) }}" style="width: 50%;display:inline">
                                Modifier
                            </a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="8">Aucun événements trouvé</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="row-fluid">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="text-align: right">
            <a class="btn btn-success" href="{{ path('event_new') }}">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Ajouter
            </a>
        </div>
    </div>
{% endblock %}

templates/event/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Creation - Evenements{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <a class="btn btn-light" href="{{ path('event_index') }}">Retour</a>
        </div>
    </div>

    <div class="row-fluid">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            {{ include('event/_form.html.twig') }}
        </div>
    </div>
{% endblock %}

templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Evenement{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
            <a class="btn btn-light" href="{{ path('event_index') }}">Retour</a>
        </div>
        <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1" style="text-align: right">
            <a class="btn btn-primary" href="{{ path('event_edit', {'id': event.id}) }}">Modifier</a>
        </div>
        <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1" style="text-align: right">
            {{ include('event/_delete_form.html.twig') }}
        </div>
    </div>
    <div class="row-fluid">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <table class="table">
                <tbody>
                <tr>
                    <th>ID</th>
                    <td>{{ event.id }}</td>
                </tr>
                <tr>
                    <th>Titre</th>
                    <td>{{ event.title }}</td>
                </tr>
                <tr>
                    <th>Description</th>
                    <td>{{ event.description }}</td>
                </tr>
                <tr>
                    <th>Déroulement</th>
                    <td>
                        {% if event.startDate|date('Y-m-d') == event.endDate|date('Y-m-d') %}
                            le {{ event.startDate|date('d/m/Y') }} de {{ event.startDate|date('H:i') }} à {{ event.endDate|date('H:i') }}
                        {% else %}
                            du {{ event.startDate ? event.startDate|date('d/m/Y à H:i') : '' }} au {{ event.endDate ? event.endDate|date('d/m/Y à H:i') : '' }}
                        {% endif %}
                    </td>
                </tr>

                <tr>
                    <th>Note</th>
                    <td>{{ event.rating }}</td>
                </tr>
                <tr>
                    <th>Association</th>
                    <td><a href="{{ path('user_show', { 'id': event.owner.id }) }}">{{ event.owner ? event.owner.name : '' }}</a></td>
                </tr>
                <tr>
                    <th>Date de publication</th>
                    <td>{{ event.publishDate ? event.publishDate|date('d/m/Y à H:i') : '' }}</td>
                </tr>
                <tr>
                    <th>Commentaires</th>
                    <td><a href="{{ path('event_list_rating', {'id': event.id}) }}">Liste des Commentaires</a></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}