src/Entity/User.php
<?php

/**
 * User class file
 *
 * PHP Version 7.1
 *
 * @category User
 * @package  User
 * @author   HumanAid <contact.humanaid@gmail.com>
 * @license  http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link     http://example.com/
 */

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * User class
 *
 * The class holding the root User class definition
 *
 * @category                                                    User
 * @package                                                     User
 * @author                                                      HumanAid <contact.humanaid@gmail.com>
 * @license                                                     http://opensource.org/licenses/gpl-license.php GPL
 * @link                                                        http://example.com/
 * @ORM\Table(name="user")
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    const ROLE_ADMIN = "ROLE_ADMIN";
    const ROLE_USER  = "ROLE_USER";
    const ROLE_COMP  = "ROLE_COMP";
    const ROLE_ASSOC = "ROLE_ASSOC";

    public static $roleTypes = [
        self::ROLE_ADMIN,
        self::ROLE_USER,
        self::ROLE_COMP,
        self::ROLE_ASSOC
    ];

    public static $roleStringTypes = [
        self::ROLE_USER  => "Utilisateur",
        self::ROLE_ADMIN => "Administrateur",
        self::ROLE_COMP  => "Companie",
        self::ROLE_ASSOC => "Association"
    ];

    /**
     * ID attribute
     *
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * Name attribute
     *
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * Manager first name attribute
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $manager_first_name;

    /**
     * Manager last name attribute
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $manager_last_name;

    /**
     * Username attribute
     *
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * Description attribute
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * Photo attribute
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * Status attribute
     *
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * Siret attribute
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $siret;

    /**
     * Landline attribute
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $landline;

    /**
     * Address attribute
     *
     * @ORM\OneToMany(
     *     targetEntity="App\Entity\Address",
     *     mappedBy="user",
     *     cascade={"persist"}
     * )
     */
    private $addresses;

    /**
     * Website attribute
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $website;

    /**
     * Email attribute
     *
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * Roles attribute
     *
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * Password attribute
     *
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * Facebook link attribute
     *
     * @ORM\Column(type="string", length=255)
     */
    private $facebook;

    /**
     * Twitter attribute
     *
     * @ORM\Column(type="string", length=255)
     */
    private $twitter;

    /**
     * Creation date attribute
     *
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * Update date attribute
     *
     * @ORM\Column(type="datetime")
     */
    private $updated_at;


    /**
     * User constructor.
     */
    public function __construct()
    {
        $this->addresses = new ArrayCollection();
    }

    /**
     * ID Getter
     *
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Manager First name Getter
     *
     * @return mixed
     */
    public function getManagerFirstName()
    {
        return $this->manager_first_name;
    }

    /**
     * Manager First name Setter
     *
     * @param mixed $manager_first_name Manager First name
     *
     * @return User
     */
    public function setManagerFirstName($manager_first_name): self
    {
        $this->manager_first_name = $manager_first_name;

        return $this;
    }

    /**
     * Manager Last name Getter
     *
     * @return mixed
     */
    public function getManagerLastName()
    {
        return $this->manager_last_name;
    }

    /**
     * Manager Last name Setter
     *
     * @param mixed $manager_last_name Manager Last name
     *
     * @return User
     */
    public function setManagerLastName($manager_last_name): self
    {
        $this->manager_last_name = $manager_last_name;

        return $this;
    }

    /**
     * Name Getter
     *
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Name Setter
     *
     * @param string $name Name
     *
     * @return $this
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Username Getter
     *
     * @return string|null
     */
    public function getUserName(): ?string
    {
        return $this->username;
    }

    /**
     * Username Setter
     *
     * @param string $username Username
     *
     * @return $this
     */
    public function setUserName(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Description Getter
     *
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Description Setter
     *
     * @param string $description Description
     *
     * @return $this
     */
    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Status Getter
     *
     * @return string|null
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Status Setter
     *
     * @param string $status Status
     *
     * @return $this
     */
    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Addresses Getter
     *
     * @return Collection|Address[]
     */
    public function getAddresses(): Collection
    {
        return $this->addresses;
    }

    /**
     * Addresses Collection Setter
     *
     * @param Address $address Address
     *
     * @return $this
     */
    public function addAddress(Address $address): self
    {
        if (!$this->addresses->contains($address)) {
            $this->addresses[] = $address;
            $address->setUser($this);
        }

        return $this;
    }

    /**
     * Addresses Collection Remover
     *
     * @param Address $address Address
     *
     * @return $this
     */
    public function removeAddress(Address $address): self
    {
        if ($this->addresses->contains($address)) {
            $this->addresses->removeElement($address);
            // set the owning side to null (unless already changed)
            if ($address->getUser() === $this) {
                $address->setUser(null);
            }
        }

        return $this;
    }

    /**
     * Website Getter
     *
     * @return string|null
     */
    public function getWebsite(): ?string
    {
        return $this->website;
    }

    /**
     * Website Setter
     *
     * @param string $website Website
     *
     * @return $this
     */
    public function setWebsite(string $website): self
    {
        $this->website = $website;

        return $this;
    }

    /**
     * Email Getter
     *
     * @return string|null
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * Email Setter
     *
     * @param string $email Email
     *
     * @return $this
     */
    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Role Getter
     *
     * @return string|null
     */
    public function getRole(): ?string
    {
        if (!empty($this->roles)) {
            return array_values($this->roles)[0];
        }

        return null;
    }

    /**
     * Roles Getter
     *
     * @return array|null
     */
    public function getRoles(): ?array
    {
        return $this->roles;
    }

    /**
     * Roles Setter
     *
     * @param array $roles Roles
     *
     * @return $this
     */
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * Salt Getter
     *
     * @return string|void|null
     */
    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     *
     * @return void
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    /**
     * Password Getter
     *
     * @return string|null
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    /**
     * Password Setter
     *

src/Controller/UserController.php
<?php

/**
 * UserController class file
 *
 * PHP Version 7.1
 *
 * @category UserController
 * @package  UserController
 * @author   HumanAid <contact.humanaid@gmail.com>
 * @license  http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link     http://example.com/
 */

namespace App\Controller;

use App\Entity\Address;
use App\Entity\User;
use App\Entity\Rating;
use App\Form\UserType;
use App\Form\UserEditType;
use App\Repository\UserRepository;
use App\Repository\RatingRepository;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

/**
 * UserController class
 *
 * The class holding the root UserController class definition
 *
 * @category       UserController
 * @package        UserController
 * @author         HumanAid <contact.humanaid@gmail.com>
 * @license        http://opensource.org/licenses/gpl-license.php GNU Public License
 * @link           http://example.com/
 * @Route("/user")
 */
class UserController extends AbstractController
{
    /**
     * Index Function
     *
     * @param UserRepository $userRepository get user repository
     *
     * @Route("/", name="user_index", methods={"GET"})
     *
     * @return Response
     */
    public function index(UserRepository $userRepository): Response
    {
        return $this->render(
            'user/index.html.twig',
            [
                'users' => $userRepository->findAll(),
            ]
        );
    }

    /**
     * New Function
     *
     * @param Request                      $request get request params
     * @param UserPasswordEncoderInterface $encoder get user password encoder
     *
     * @Route("/new", name="user_new", methods={"GET","POST"})
     *
     * @return Response
     * @throws Exception
     */
    public function new(
        Request $request,
        UserPasswordEncoderInterface $encoder
    ): Response {
        $form = $this->createForm(
            UserType::class,
            $user = new User(),
            [
                'method' => 'POST',
                'attr' => [
                    'id'     => 'new_user'
                ]
            ]
        )->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if (!$this->isCsrfTokenValid(
                'user_item',
                $request->request->get('user')['_token']
            )
            ) {
                throw new AccessDeniedException('Formulaire invalide');
            }

            $user->setPassword(
                $encoder->encodePassword(
                    $user,
                    $form->get('password')->getData()
                )
            );
            $user->setRoles(
                [
                    $form->get('roles')->getData()
                ]
            );
            $user->setCreatedAt(new \DateTime());
            $user->setUpdatedAt(new \DateTime());
            $entityManager = $this->getDoctrine()->getManager();

            /**
             * Address
             *
             * @var Address $address
             */
            foreach ($form->get('addresses')->getData() as $address) {
                $user->addAddress($address);
                $address->setUser($user);
                $entityManager->persist($address);
            }

            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render(
            'user/new.html.twig',
            [
                'user' => $user,
                'form' => $form->createView(),
            ]
        );
    }

    /**
     * Show Function
     *
     * @param User $user get user to show
     *
     * @Route("/{id}", name="user_show", methods={"GET"})
     *
     * @return Response response
     */
    public function show(User $user): Response
    {
        return $this->render(
            'user/show.html.twig',
            [
                'user' => $user,
            ]
        );
    }

    /**
     * Edit Function
     *
     * @param Request                      $request get request params
     * @param User                         $user    get user to edit
     * @param UserPasswordEncoderInterface $encoder get user password encoder
     *
     * @Route("/{id}/edit", name="user_edit", methods={"GET","POST"})
     *
     * @return Response
     */
    public function edit(
        Request $request,
        User $user,
        UserPasswordEncoderInterface $encoder
    ): Response {
        $form = $this->createForm(UserEditType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if (!$this->isCsrfTokenValid(
                'user_edit_item',
                $request->request->get('user_edit')['_token']
            )
            ) {
                throw new AccessDeniedException('Formulaire invalide');
            }

            $em = $this->getDoctrine()->getManager();

            /**
             * Address
             *
             * @var Address $address
             */
            foreach ($form->get('addresses')->getData() as $address) {
                $user->addAddress($address);
                $address->setUser($user);
                $em->persist($address);
            }

            $em->flush();
            return $this->redirectToRoute('user_index');
        }

        return $this->render(
            'user/edit.html.twig',
            [
                'user' => $user,
                'form' => $form->createView(),
            ]
        );
    }

    /**
     * Delete Function
     *
     * @param Request $request get request params
     * @param User    $user    get user to delete
     *
     * @Route("/{id}", name="user_delete", methods={"DELETE"})
     *
     * @return Response
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid(
            'delete'.$user->getId(),
            $request->request->get('_token')
        )
        ) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_index');
    }

    /**
     * ListRating Function
     *
     * @param RatingRepository $ratingRepository get rating repository
     *
     * @Route("/rating/{id}", name="user_list_rating", methods={"GET"},)
     * 
     *
     * @return Response
     */
    public function listrating(RatingRepository $ratingRepository, Request $request, Rating $rating ): Response
    {
        $ratingRepository = $this->getDoctrine()->getManager()
            ->getRepository(Rating::class);

        $id = $request->get("id");
        $result = $ratingRepository->findByUser($id);



        return $this->render(
            'rating/index.html.twig',
            [
                'ratings' => $result,
            ]
        );
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Êtes vous sûre de vouloir faire ca ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_row(form._token) }}
    {{ form_errors(form) }}

    <div class="form-group">
        {{ form_label(form.roles) }}
        {{ form_widget(form.roles.vars.prototype) }}
        {% if form_errors(form.roles.vars.prototype) %}
            <div class="alert alert-danger" role="alert">
                {{ form_errors(form.roles.vars.prototype) }}
            </div>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form_label(form.name) }}
        {{ form_widget(form.name) }}
        {% if form_errors(form.name) %}
            <div class="alert alert-danger" role="alert">
                {{ form_errors(form.name) }}
            </div>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form_label(form.username) }}
        {{ form_widget(form.username) }}
        {% if form_errors(form.username) %}
            <div class="alert alert-danger" role="alert">
                {{ form_errors(form.username) }}
            </div>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form_label(form.email) }}
        {{ form_widget(form.email) }}
        {% if form_errors(form.email) %}
            <div class="alert alert-danger" role="alert">
                {{ form_errors(form.email) }}
            </div>
        {% endif %}
    </div>

    {% for passwordField in form.password %}
        <div class="form-group">
            {{ form_label(passwordField) }}
            {{ form_widget(passwordField) }}
            {% if form_errors(passwordField) %}
                <div class="alert alert-danger" role="alert">
                    {{ form_errors(passwordField) }}
                </div>
            {% endif %}
        </div>
    {% endfor %}

    <div class="form-group">
        {{ form_label(form.landline) }}
        {{ form_widget(form.landline) }}
        {% if form_errors(form.landline) %}
            <div class="alert alert-danger" role="alert">
                {{ form_errors(form.landline) }}
            </div>
        {% endif %}
    </div>

    {{ form_label(form.addresses) }}
    {% import 'user/_macro.html.twig' as formMacro %}
    <div class="jumbotron" id="addresses" data-prototype="{{ formMacro.printAddressRow(form.addresses.vars.prototype)|e('html_attr') }}">
        <div id="address_1" class="address">
            {% for address in form.addresses %}
                <div class="form-group">
                    {{ form_label(address) }}
                    {{ form_widget(address) }}
                    {% if form_errors(address) %}
                        <div class="alert alert-danger" role="alert">
                            {{ form_errors(address) }}
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>

        <button type="button" class="btn btn-success" id="add_address">Ajouter une adresse</button>
    </div>

    <div class="jumbotron">
        <div class="form-group">
            {{ form_label(form.manager_first_name) }}
            {{ form_widget(form.manager_first_name) }}
            {% if form_errors(form.manager_first_name) %}
                <div class="alert alert-danger" role="alert">
                    {{ form_errors(form.manager_first_name) }}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form_label(form.manager_last_name) }}
            {{ form_widget(form.manager_last_name) }}
            {% if form_errors(form.manager_last_name) %}
                <div class="alert alert-danger" role="alert">
                    {{ form_errors(form.manager_last_name) }}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form_label(form.website) }}
            {{ form_widget(form.website) }}
            {% if form_errors(form.website) %}
                <div class="alert alert-danger" role="alert">
                    {{ form_errors(form.website) }}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form_label(form.description) }}
            {{ form_widget(form.description) }}
            {% if form_errors(form.description) %}
                <div class="alert alert-danger" role="alert">
                    {{ form_errors(form.description) }}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form_label(form.siret) }}
            {{ form_widget(form.siret) }}
            {% if form_errors(form.siret) %}
                <div class="alert alert-danger" role="alert">
                    {{ form_errors(form.siret) }}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form_label(form.status) }}
            {{ form_widget(form.status) }}
            {% if form_errors(form.status) %}
                <div class="alert alert-danger" role="alert">
                    {{ form_errors(form.status) }}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form_label(form.facebook) }}
            {{ form_widget(form.facebook) }}
            {% if form_errors(form.facebook) %}
                <div class="alert alert-danger" role="alert">
                    {{ form_errors(form.facebook) }}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form_label(form.twitter) }}
            {{ form_widget(form.twitter) }}
            {% if form_errors(form.twitter) %}
                <div class="alert alert-danger" role="alert">
                    {{ form_errors(form.twitter) }}
                </div>
            {% endif %}
        </div>
    </div>

    <div class="form-group">
        <button class="btn btn-success">{{ button_label|default('Enregistrer') }}</button>
    </div>
{{ form_end(form, {'render_rest': false}) }}

templates/user/_macro.html.twig
{% macro printAddressRow(form) %}
    {% block _address_entry_widget %}
        <div class="form-group" id="inputAddress">
            {{ form_label(form) }}
            {{ form_widget(form) }}
            {% if form_errors(form) %}
                <div class="alert alert-danger" role="alert">
                    {{ form_errors(form) }}
                </div>
            {% endif %}
        </div>
    {% endblock %}
{% endmacro %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
 {% set roles = '' %}
    <div class="row-fluid">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="text-align: right">
            <a class="btn btn-success" href="{{ path('user_new') }}">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Ajouter
            </a>
        </div>
    </div>
    <div class="row-fluid">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <table class="table table-global">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Username</th>
                        <th>Email</th>
                        <th>Description</th>
                        <th>Siret</th>
                        <th>Address</th>
                        <th>Website</th>
                        <th>Status</th>
                        <th>Roles</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for user in users %}
                {% if 'ROLE_ASSOC' in user.roles %}
                    {% set roles = 'Association' %}
                {% elseif 'ROLE_COMP' in user.roles %}
                    {% set roles = 'Entreprise' %}
                {% elseif 'ROLE_ADMIN' in user.roles %}
                    {% set roles = 'Admin' %}
                {% elseif 'ROLE_USER' in user.roles %}
                    {% set roles = 'Utilisateur' %}
                {% endif %}
                    <tr>
                        <td>{{ user.id }}</td>
                        <td>{{ user.name }}</td>
                        <td>{{ user.username }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.description }}</td>
                        <td>{{ user.siret }}</td>
                        <td>{% if user.addresses is not empty %}{{ user.addresses|first }}{% endif %}</td>
                        <td>{{ user.website }}</td>
                        <td>{{ user.status }}</td>
                        <td>{{ roles }}</td>
                        <td class="actions">
                            <a class="btn btn-info" href="{{ path('user_show', {'id': user.id}) }}" style="width: 50%;display:inline;">
                                Voir
                            </a>
                            <a class="btn btn-primary" href="{{ path('user_edit', {'id': user.id}) }}" style="width: 50%;display:inline">
                                Modifier
                            </a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="11">Aucun utilisateurs trouvé</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
            <a class="btn btn-light" href="{{ path('user_index') }}">Retour</a>
        </div>
        <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1" style="text-align: right">
            <a class="btn btn-primary" href="{{ path('user_edit', {'id': user.id}) }}">Modifier</a>
        </div>
        <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1" style="text-align: right">
            {{ include('user/_delete_form.html.twig') }}
        </div>
    </div>
    <div class="row-fluid">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <table class="table">
                <tbody>
                    <tr>
                        <th>Id</th>
                        <td>{{ user.id }}</td>
                    </tr>
                    <tr>
                        <th>Name</th>
                        <td>{{ user.name }}</td>
                    </tr>
                    <tr>
                        <th>Username</th>
                        <td>{{ user.username }}</td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td>{{ user.email }}</td>
                    </tr>
                    <tr>
                        <th>Téléphone</th>
                        <td>{{ user.landline }}</td>
                    </tr>
                    <tr>
                        <th>Description</th>
                        <td>{{ user.description }}</td>
                    </tr>
                    <tr>
                        <th>Adresse actuelle</th>
                        <td>{{ user.addresses|first }}</td>
                    </tr>
                    {% if 'ROLE_ASSOC' in user.roles or 'ROLE_COMP' in user.roles %}
                        <tr>
                            <th>Manager</th>
                            <td>{{ user.managerLastName ~ " " ~ user.managerFirstName }}</td>
                        </tr>
                        <tr>
                            <th>Status</th>
                            <td>{{ user.status }}</td>
                        </tr>
                        <tr>
                            <th>Siret</th>
                            <td>{{ user.siret }}</td>
                        </tr>
                        <tr>
                            <th>Website</th>
                            <td><a href="{{ user.website }}">{{ user.website }}</a></td>
                        </tr>
                        <tr>
                            <th>Facebook</th>
                            <td><a href="{{ user.facebook }}">{{ user.facebook }}</a></td>
                        </tr>
                        <tr>
                            <th>Twitter</th>
                            <td><a href="{{ user.twitter }}">{{ user.twitter }}</a></td>
                        </tr>
                    {% endif %}
                    <tr>
                    {% if 'ROLE_ASSOC' in user.roles %}
                        {% set roles = 'Association' %}
                    {% elseif 'ROLE_COMP' in user.roles %}
                        {% set roles = 'Entreprise' %}
                    {% elseif 'ROLE_ADMIN' in user.roles %}
                        {% set roles = 'Admin' %}
                    {% elseif 'ROLE_USER' in user.roles %}
                        {% set roles = 'Utilisateur' %}
                    {% endif %}
                        <th>Roles</th>
                        <td>{{ roles }}</td>
                    </tr>
                    {% if user.createdAt|date('d/m/Y') != "30/11/-0001" %}
                        <tr>
                            <th>Créé le</th>
                            <td>{{ user.createdAt|date('d/m/Y à H:i') }}</td>
                        </tr>
                    {% endif %}
                    {% if user.updatedAt|date('d/m/Y') != "30/11/-0001"  %}
                        <tr>
                            <th>Modifié le</th>
                            <td>{{ user.updatedAt|date('d/m/Y à H:i') }}</td>
                        </tr>
                    {% endif %}
                        <tr>
                            <th>Commentaires</th>
                            <td><a href="{{ path('user_list_rating', {'id': user.id}) }}">Liste des Commentaires</a></td>
                        </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}